#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: build.bat