#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: build.bat

#disabled test execution. build script already runs all tests.
test: off